# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  elbow_pitch_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  elbow_roll_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  shoulder_pan_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  shoulder_pitch_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  shoulder_yaw_joint:
    has_velocity_limits: false
    has_acceleration_limits: false
  wrist_pitch_joint:
    has_velocity_limits: false
    has_acceleration_limits: false